export const combatEngravings = {
    'ADRENALINE': 'Adrenaline',
    'ALL-OUT_ATTACK': 'All-Out Attack',
    'AMBUSH_MASTER': 'Ambush Master',
    'AWAKENING': 'Awakening',
    'BARRICADE': 'Barricade',
    'BROKEN_BONE': 'Broken Bone',
    'CONTENDER': 'Contender',
    'CRISIS_EVASION': 'Crisis Evasion',
    'CRUSHING_FIST': 'Crushing Fist',
    'CURSED_DOLL': 'Cursed Doll',
    'DISRESPECT': 'Disrespect',
    'DIVINE_PROTECTION': 'Divine Protection',
    'DROPS_OF_ETHER': 'Drops of Ether',
    'EMERGENCY_RESCUE': 'Emergency Rescue',
    'ENHANCED_SHIELD': 'Enhanced Shield',
    'ETHER_PREDATOR': 'Ether Predator',
    'EXPERT': 'Expert',
    'EXPLOSIVE_EXPERT': 'Explosive Expert',
    'FORTITUDE': 'Fortitude',
    'GRUDGE': 'Grudge',
    'HEAVY_ARMOR': 'Heavy Armor',
    'HIT_MASTER': 'Hit Master',
    'KEEN_BLUNT_WEAPON': 'Keen Blunt Weapon',
    'LIGHTNING_FURY': 'Lightning Fury',
    'MAGICK_STREAM': 'Magick Stream',
    'MASS_INCREASE': 'Mass Increase',
    'MASTER_BRAWLER': 'Master Brawler',
    'MASTER_OF_ESCAPE': 'Master of Escape',
    'MASTER_TENACITY': 'Master\'s Tenacity',
    'MAX_MP_INCREASE': 'Max MP Increase',
    'MP_EFFICIENCY_INCREASE': 'MP Efficiency Increase',
    'NECROMANCY': 'Necromancy',
    'PRECISE_DAGGER': 'Precise Dagger',
    'PREEMPTIVE_STRIKE': 'Preemptive Strike',
    'PROPULSION': 'Propulsion',
    'RAID_CAPTAIN': 'Raid Captain',
    'SHIELD_PIERCING': 'Shield Piercing',
    'SIGHT_FOCUS': 'Sight Focus',
    'SPIRIT_ABSORPTION': 'Spirit Absorption',
    'STABILIZED_STATUS': 'Stabilized Status',
    'STRONG_WILL': 'Strong Will',
    'SUPER_CHARGE': 'Super Charge',
    'VITAL_POINT_HIT': 'Vital Point Hit',
}

export const classEngravings = {
    'REMAINING_ENERGY': 'Remaining Energy',
    'SURGE': 'Surge',
    'HUNGER': 'Hunger',
    'LUNAR_VOICE': 'Lunar Voice',
    'DEMONIC_IMPULSE': 'Demonic Impulse',
    'PERFECT_SUPPRESSION': 'Perfect Suppression',
    'BARRAGE_ENHANCEMENT': 'Barrage Enhancement',
    'FIREPOWER_ENHANCEMENT': 'Firepower Enhancement',
    'ENHANCED_WEAPON': 'Enhanced Weapon',
    'PISTOLEER': 'Pistoleer',
    'PEACEMAKER': 'Peacemaker',
    'TIME_TO_HUNT': 'Time to Hunt',
    'ARTHETINEAN_SKILL': 'Arthetinean Skill',
    'EVOLUTIONARY_LEGACY': 'Evolutionary Legacy',
    'DEATH_STRIKE': 'Death Strike',
    'LOYAL_COMPANION': 'Loyal Companion',
    'EMPRESS_GRACE': "Empress's Grace",
    'ORDER_OF_THE_EMPEROR': 'Order of the Emperor',
    'DESPERATE_SALVATION': 'Desperate Salvation',
    'TRUE_COURAGE': 'True Courage',
    'IGNITER': 'Igniter',
    'REFLUX': 'Reflux',
    'COMMUNICATION_OVERFLOW': 'Communication Overflow',
    'MASTER_SUMMONER': 'Master Summoner',
    'CONTROL': 'Control',
    'PINNACLE': 'Pinnacle',
    'SHOCK_TRAINING': 'Shock Training',
    'ULTIMATE_SKILL_TAIJUTSU': 'Ultimate Skill: Taijutsu',
    'ENERGY_OVERFLOW': 'Energy Overflow',
    'ROBUST_SPIRIT': 'Robust Spirit',
    'DEATHBLOW': 'Deathblow',
    'ESOTERIC_FLURRY': 'Esoteric Flurry',
    'ESOTERIC_SKILL_ENHANCEMENT': 'Esoteric Skill Enhancement',
    'FIRST_INTENTION': 'First Intention',
    'DRIZZLE': 'Drizzle',
    'WIND_FURY': 'Wind Fury',
    'FULL_BLOOM': 'Full Bloom',
    'RECURRENCE': 'Recurrence',
    'BERSERKERS_TECHNIQUE': "Berserker's Technique",
    'MAYHEM': 'Mayhem',
    'GRAVITY_TRAINING': 'Gravity Training',
    'RAGE_HAMMER': 'Rage Hammer',
    'COMBAT_READINESS': 'Combat Readiness',
    'LONE_KNIGHT': 'Lone Knight',
    'BLESSED_AURA': 'Blessed Aura',
    'JUDGMENT': 'Judgment',
    'PREDATOR': 'Predator',
    'PUNISHER': 'Punisher',
    'FULL_MOON_HARVESTER': 'Full Moon Harvester',
    'NIGHT_EDGE': 'Night\'s Edge',
}

export const engravings = {
    'REMAINING_ENERGY': 'Remaining Energy',
    'SURGE': 'Surge',
    'HUNGER': 'Hunger',
    'LUNAR_VOICE': 'Lunar Voice',
    'DEMONIC_IMPULSE': 'Demonic Impulse',
    'PERFECT_SUPPRESSION': 'Perfect Suppression',
    'BARRAGE_ENHANCEMENT': 'Barrage Enhancement',
    'FIREPOWER_ENHANCEMENT': 'Firepower Enhancement',
    'ENHANCED_WEAPON': 'Enhanced Weapon',
    'PISTOLEER': 'Pistoleer',
    'PEACEMAKER': 'Peacemaker',
    'TIME_TO_HUNT': 'Time to Hunt',
    'ARTHETINEAN_SKILL': 'Arthetinean Skill',
    'EVOLUTIONARY_LEGACY': 'Evolutionary Legacy',
    'DEATH_STRIKE': 'Death Strike',
    'LOYAL_COMPANION': 'Loyal Companion',
    'EMPRESS_GRACE': "Empress's Grace",
    'ORDER_OF_THE_EMPEROR': 'Order of the Emperor',
    'DESPERATE_SALVATION': 'Desperate Salvation',
    'TRUE_COURAGE': 'True Courage',
    'IGNITER': 'Igniter',
    'REFLUX': 'Reflux',
    'COMMUNICATION_OVERFLOW': 'Communication Overflow',
    'MASTER_SUMMONER': 'Master Summoner',
    'CONTROL': 'Control',
    'PINNACLE': 'Pinnacle',
    'SHOCK_TRAINING': 'Shock Training',
    'ULTIMATE_SKILL_TAIJUTSU': 'Ultimate Skill: Taijutsu',
    'ENERGY_OVERFLOW': 'Energy Overflow',
    'ROBUST_SPIRIT': 'Robust Spirit',
    'DEATHBLOW': 'Deathblow',
    'ESOTERIC_FLURRY': 'Esoteric Flurry',
    'ESOTERIC_SKILL_ENHANCEMENT': 'Esoteric Skill Enhancement',
    'FIRST_INTENTION': 'First Intention',
    'DRIZZLE': 'Drizzle',
    'WIND_FURY': 'Wind Fury',
    'FULL_BLOOM': 'Full Bloom',
    'RECURRENCE': 'Recurrence',
    'BERSERKERS_TECHNIQUE': "Berserker's Technique",
    'MAYHEM': 'Mayhem',
    'GRAVITY_TRAINING': 'Gravity Training',
    'RAGE_HAMMER': 'Rage Hammer',
    'COMBAT_READINESS': 'Combat Readiness',
    'LONE_KNIGHT': 'Lone Knight',
    'BLESSED_AURA': 'Blessed Aura',
    'JUDGMENT': 'Judgment',
    'PREDATOR': 'Predator',
    'PUNISHER': 'Punisher',
    'FULL_MOON_HARVESTER': 'Full Moon Harvester',
    'NIGHT_EDGE': 'Night\'s Edge',
    'ADRENALINE': 'Adrenaline',
    'ALL-OUT_ATTACK': 'All-Out Attack',
    'AMBUSH_MASTER': 'Ambush Master',
    'AWAKENING': 'Awakening',
    'BARRICADE': 'Barricade',
    'BROKEN_BONE': 'Broken Bone',
    'CONTENDER': 'Contender',
    'CRISIS_EVASION': 'Crisis Evasion',
    'CRUSHING_FIST': 'Crushing Fist',
    'CURSED_DOLL': 'Cursed Doll',
    'DISRESPECT': 'Disrespect',
    'DIVINE_PROTECTION': 'Divine Protection',
    'DROPS_OF_ETHER': 'Drops of Ether',
    'EMERGENCY_RESCUE': 'Emergency Rescue',
    'ENHANCED_SHIELD': 'Enhanced Shield',
    'ETHER_PREDATOR': 'Ether Predator',
    'EXPERT': 'Expert',
    'EXPLOSIVE_EXPERT': 'Explosive Expert',
    'FORTITUDE': 'Fortitude',
    'GRUDGE': 'Grudge',
    'HEAVY_ARMOR': 'Heavy Armor',
    'HIT_MASTER': 'Hit Master',
    'KEEN_BLUNT_WEAPON': 'Keen Blunt Weapon',
    'LIGHTNING_FURY': 'Lightning Fury',
    'MAGICK_STREAM': 'Magick Stream',
    'MASS_INCREASE': 'Mass Increase',
    'MASTER_BRAWLER': 'Master Brawler',
    'MASTER_OF_ESCAPE': 'Master of Escape',
    'MASTER_TENACITY': 'Master\'s Tenacity',
    'MAX_MP_INCREASE': 'Max MP Increase',
    'MP_EFFICIENCY_INCREASE': 'MP Efficiency Increase',
    'NECROMANCY': 'Necromancy',
    'PRECISE_DAGGER': 'Precise Dagger',
    'PREEMPTIVE_STRIKE': 'Preemptive Strike',
    'PROPULSION': 'Propulsion',
    'RAID_CAPTAIN': 'Raid Captain',
    'SHIELD_PIERCING': 'Shield Piercing',
    'SIGHT_FOCUS': 'Sight Focus',
    'SPIRIT_ABSORPTION': 'Spirit Absorption',
    'STABILIZED_STATUS': 'Stabilized Status',
    'STRONG_WILL': 'Strong Will',
    'SUPER_CHARGE': 'Super Charge',
    'VITAL_POINT_HIT': 'Vital Point Hit',
}

export const engravingLevels = [
    3,
    6,
    9,
    12,
]