export const combatEngravings = {
    ADRENALINE: 'Adrenaline',
    ALL_OUT_ATTACK: 'All-Out Attack',
    AMBUSH_MASTER: 'Ambush Master',
    AWAKENING: 'Awakening',
    BARRICADE: 'Barricade',
    BROKEN_BONE: 'Broken Bone',
    CONTENDER: 'Contender',
    CRISIS_EVASION: 'Crisis Evasion',
    CRUSHING_FIST: 'Crushing Fist',
    CURSED_DOLL: 'Cursed Doll',
    DISRESPECT: 'Disrespect',
    DIVINE_PROTECTION: 'Divine Protection',
    DROPS_OF_ETHER: 'Drops of Ether',
    EMERGENCY_RESCUE: 'Emergency Rescue',
    ENHANCED_SHIELD: 'Enhanced Shield',
    ETHER_PREDATOR: 'Ether Predator',
    EXPERT: 'Expert',
    EXPLOSIVE_EXPERT: 'Explosive Expert',
    FORTITUDE: 'Fortitude',
    GRUDGE: 'Grudge',
    HEAVY_ARMOR: 'Heavy Armor',
    HIT_MASTER: 'Hit Master',
    KEEN_BLUNT_WEAPON: 'Keen Blunt Weapon',
    LIGHTNING_FURY: 'Lightning Fury',
    MAGICK_STREAM: 'Magick Stream',
    MASS_INCREASE: 'Mass Increase',
    MASTER_BRAWLER: 'Master Brawler',
    MASTER_OF_ESCAPE: 'Master of Escape',
    MASTER_TENACITY: "Master's Tenacity",
    MAX_MP_INCREASE: 'Max MP Increase',
    MP_EFFICIENCY_INCREASE: 'MP Efficiency Increase',
    NECROMANCY: 'Necromancy',
    PRECISE_DAGGER: 'Precise Dagger',
    PREEMPTIVE_STRIKE: 'Preemptive Strike',
    PROPULSION: 'Propulsion',
    RAID_CAPTAIN: 'Raid Captain',
    SHIELD_PIERCING: 'Shield Piercing',
    SIGHT_FOCUS: 'Sight Focus',
    SPIRIT_ABSORPTION: 'Spirit Absorption',
    STABILIZED_STATUS: 'Stabilized Status',
    STRONG_WILL: 'Strong Will',
    SUPER_CHARGE: 'Super Charge',
    VITAL_POINT_HIT: 'Vital Point Hit'
  }

export const classEngravings = {
    ARTHETINEAN_SKILL: 'Arthetinean Skill',
    BARRAGE_ENHANCEMENT: 'Barrage Enhancement',
    BERSERKERS_TECHNIQUE: "Berserker's Technique",
    BLESSED_AURA: 'Blessed Aura',
    COMBAT_READINESS: 'Combat Readiness',
    COMMUNICATION_OVERFLOW: 'Communication Overflow',
    CONTROL: 'Control',
    DEATHBLOW: 'Deathblow',
    DEATH_STRIKE: 'Death Strike',
    DEMONIC_IMPULSE: 'Demonic Impulse',
    DESPERATE_SALVATION: 'Desperate Salvation',
    DRIZZLE: 'Drizzle',
    EMPRESS_GRACE: "Empress's Grace",
    ENERGY_OVERFLOW: 'Energy Overflow',
    ENHANCED_WEAPON: 'Enhanced Weapon',
    ESOTERIC_FLURRY: 'Esoteric Flurry',
    ESOTERIC_SKILL_ENHANCEMENT: 'Esoteric Skill Enhancement',
    EVOLUTIONARY_LEGACY: 'Evolutionary Legacy',
    FIREPOWER_ENHANCEMENT: 'Firepower Enhancement',
    FIRST_INTENTION: 'First Intention',
    FULL_BLOOM: 'Full Bloom',
    FULL_MOON_HARVESTER: 'Full Moon Harvester',
    GRAVITY_TRAINING: 'Gravity Training',
    HUNGER: 'Hunger',
    IGNITER: 'Igniter',
    JUDGMENT: 'Judgment',
    LONE_KNIGHT: 'Lone Knight',
    LOYAL_COMPANION: 'Loyal Companion',
    LUNAR_VOICE: 'Lunar Voice',
    MASTER_SUMMONER: 'Master Summoner',
    MAYHEM: 'Mayhem',
    NIGHT_EDGE: "Night's Edge",
    ORDER_OF_THE_EMPEROR: 'Order of the Emperor',
    PEACEMAKER: 'Peacemaker',
    PERFECT_SUPPRESSION: 'Perfect Suppression',
    PINNACLE: 'Pinnacle',
    PISTOLEER: 'Pistoleer',
    PREDATOR: 'Predator',
    PUNISHER: 'Punisher',
    RAGE_HAMMER: 'Rage Hammer',
    RECURRENCE: 'Recurrence',
    REFLUX: 'Reflux',
    REMAINING_ENERGY: 'Remaining Energy',
    ROBUST_SPIRIT: 'Robust Spirit',
    SHOCK_TRAINING: 'Shock Training',
    SURGE: 'Surge',
    TIME_TO_HUNT: 'Time to Hunt',
    TRUE_COURAGE: 'True Courage',
    ULTIMATE_SKILL_TAIJUTSU: 'Ultimate Skill: Taijutsu',
    WIND_FURY: 'Wind Fury'
  }

export const engravings = {
    ADRENALINE: 'Adrenaline',
    ALL_OUT_ATTACK: 'All-Out Attack',
    AMBUSH_MASTER: 'Ambush Master',
    ARTHETINEAN_SKILL: 'Arthetinean Skill',
    AWAKENING: 'Awakening',
    BARRAGE_ENHANCEMENT: 'Barrage Enhancement',
    BARRICADE: 'Barricade',
    BERSERKERS_TECHNIQUE: "Berserker's Technique",
    BLESSED_AURA: 'Blessed Aura',
    BROKEN_BONE: 'Broken Bone',
    COMBAT_READINESS: 'Combat Readiness',
    COMMUNICATION_OVERFLOW: 'Communication Overflow',
    CONTENDER: 'Contender',
    CONTROL: 'Control',
    CRISIS_EVASION: 'Crisis Evasion',
    CRUSHING_FIST: 'Crushing Fist',
    CURSED_DOLL: 'Cursed Doll',
    DEATHBLOW: 'Deathblow',
    DEATH_STRIKE: 'Death Strike',
    DEMONIC_IMPULSE: 'Demonic Impulse',
    DESPERATE_SALVATION: 'Desperate Salvation',
    DISRESPECT: 'Disrespect',
    DIVINE_PROTECTION: 'Divine Protection',
    DRIZZLE: 'Drizzle',
    DROPS_OF_ETHER: 'Drops of Ether',
    EMERGENCY_RESCUE: 'Emergency Rescue',
    EMPRESS_GRACE: "Empress's Grace",
    ENERGY_OVERFLOW: 'Energy Overflow',
    ENHANCED_SHIELD: 'Enhanced Shield',
    ENHANCED_WEAPON: 'Enhanced Weapon',
    ESOTERIC_FLURRY: 'Esoteric Flurry',
    ESOTERIC_SKILL_ENHANCEMENT: 'Esoteric Skill Enhancement',
    ETHER_PREDATOR: 'Ether Predator',
    EVOLUTIONARY_LEGACY: 'Evolutionary Legacy',
    EXPERT: 'Expert',
    EXPLOSIVE_EXPERT: 'Explosive Expert',
    FIREPOWER_ENHANCEMENT: 'Firepower Enhancement',
    FIRST_INTENTION: 'First Intention',
    FORTITUDE: 'Fortitude',
    FULL_BLOOM: 'Full Bloom',
    FULL_MOON_HARVESTER: 'Full Moon Harvester',
    GRAVITY_TRAINING: 'Gravity Training',
    GRUDGE: 'Grudge',
    HEAVY_ARMOR: 'Heavy Armor',
    HIT_MASTER: 'Hit Master',
    HUNGER: 'Hunger',
    IGNITER: 'Igniter',
    JUDGMENT: 'Judgment',
    KEEN_BLUNT_WEAPON: 'Keen Blunt Weapon',
    LIGHTNING_FURY: 'Lightning Fury',
    LONE_KNIGHT: 'Lone Knight',
    LOYAL_COMPANION: 'Loyal Companion',
    LUNAR_VOICE: 'Lunar Voice',
    MAGICK_STREAM: 'Magick Stream',
    MASS_INCREASE: 'Mass Increase',
    MASTER_BRAWLER: 'Master Brawler',
    MASTER_OF_ESCAPE: 'Master of Escape',
    MASTER_SUMMONER: 'Master Summoner',
    MASTER_TENACITY: "Master's Tenacity",
    MAX_MP_INCREASE: 'Max MP Increase',
    MAYHEM: 'Mayhem',
    MP_EFFICIENCY_INCREASE: 'MP Efficiency Increase',
    NECROMANCY: 'Necromancy',
    NIGHT_EDGE: "Night's Edge",
    ORDER_OF_THE_EMPEROR: 'Order of the Emperor',
    PEACEMAKER: 'Peacemaker',
    PERFECT_SUPPRESSION: 'Perfect Suppression',
    PINNACLE: 'Pinnacle',
    PISTOLEER: 'Pistoleer',
    PRECISE_DAGGER: 'Precise Dagger',
    PREDATOR: 'Predator',
    PREEMPTIVE_STRIKE: 'Preemptive Strike',
    PROPULSION: 'Propulsion',
    PUNISHER: 'Punisher',
    RAGE_HAMMER: 'Rage Hammer',
    RAID_CAPTAIN: 'Raid Captain',
    RECURRENCE: 'Recurrence',
    REFLUX: 'Reflux',
    REMAINING_ENERGY: 'Remaining Energy',
    ROBUST_SPIRIT: 'Robust Spirit',
    SHIELD_PIERCING: 'Shield Piercing',
    SHOCK_TRAINING: 'Shock Training',
    SIGHT_FOCUS: 'Sight Focus',
    SPIRIT_ABSORPTION: 'Spirit Absorption',
    STABILIZED_STATUS: 'Stabilized Status',
    STRONG_WILL: 'Strong Will',
    SUPER_CHARGE: 'Super Charge',
    SURGE: 'Surge',
    TIME_TO_HUNT: 'Time to Hunt',
    TRUE_COURAGE: 'True Courage',
    ULTIMATE_SKILL_TAIJUTSU: 'Ultimate Skill: Taijutsu',
    VITAL_POINT_HIT: 'Vital Point Hit',
    WIND_FURY: 'Wind Fury'
  }

export const bookLevels = {
    '3': 3,
    '6': 6,
    '9': 9,
    '12': 12,
}

export const stoneLevels = {
    '0': 0, 
    '1': 1, 
    '2': 2, 
    '3': 3, 
    '4': 4, 
    '5': 5, 
    '6': 6, 
    '7': 7, 
    '8': 8, 
    '9': 9, 
    '10': 10,
}

export const engravingLevels = {
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
}

export const getEngravingLevels = () => {
    return {
        '3': 3,
        '4': 4,
        '5': 5,
        '6': 6,
    }
}